Add Casertavecchia (Italy)
dpshelio/Travel-guide pull request #1
Opened 2020-10-15 12:00 UTC by twemyss

This pull request adds basic details on the village of Casertavecchia (Italy). It also updates the README page for Europe to have a link to the village.

2020-10-21 18:27 UTC, dpshelio requested changes
Please, update with the suggested changes.

2020-10-21 18:27 UTC, dpshelio commented on europe/README.md
> +
Hey! you forgot to add the country first, i.e., italy and its file, `italy.md`

2020-10-21 18:27 UTC, dpshelio commented on europe/README.md
> +- [Casertavecchia](/europe/italy/casertavecchia.md)
```suggestion
- [Casertavecchia](./italy/casertavecchia.md)
```

2020-10-21 22:09 UTC, twemyss commented
Thanks David - I have added the country README as requested, and updated the links accordingly.

2020-10-22 15:12 UTC, dpshelio approved these changes
👏

2020-10-22 15:12 UTC, merged