Adding caribbean subfolder & barbados page to travel guide
dpshelio/Travel-guide pull request #3
Opened 2020-10-15 12:38 UTC by sdm03

Added caribbean subfolder in north america directory
Added barbados.md file to caribbean folder

2020-10-21 18:33 UTC, dpshelio requested changes
small problem with the link

2020-10-21 18:33 UTC, dpshelio commented on north_america/README.md
> +  - [caribbean/](./caribbean)
```suggestion
  - [caribbean](./caribbean/README.md)
```

2020-10-21 18:36 UTC, dpshelio approved these changes
I've fixed the problem and now it can be included

2020-10-21 18:36 UTC, merged

2020-10-22 09:38 UTC, sdm03 commented
Thank you!