Must see: Swedish Lapland
dpshelio/Travel-guide pull request #31
Opened 2020-10-18 21:56 UTC by nuttamas

Must see: Swedish Lapland. This is the most beautiful place in Sweden.

2020-10-22 18:09 UTC, dpshelio requested changes

2020-10-22 18:09 UTC, dpshelio commented on europe/Sweden/README.md
> +Most recommended
😱 we don't have a title!

2020-10-22 18:09 UTC, dpshelio commented on europe/Sweden/Abisko.md
> +Abisko is a national park in the Northernmosr part of Sweden. Swedish lapland is gorgeous in Autumn. The place ie well-preserved. The weather is cool and fresh. There are many hiking trails to try ou
we are missing a title 😱

2020-10-29 10:49 UTC, nuttamas commented
Resolved - Added the titles to both files

2020-10-29 10:49 UTC, closed without merging